//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST_Message.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Message.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Diagnostics.Contracts;
        ///using ABC;
        ///partial class PoirotMain
        ///{
        ///    static void check_Assertion()
        ///    {
        ///        Contract.Assert(
        ///                 (!(GlobalObjectsForCST.C.conclusion.largestParty == &quot;Alice&quot;) ||
        ///                 ((GlobalObjectsForCST.A.data &gt;= GlobalObjectsForCST.B.data) &amp;&amp; (GlobalObjectsForCST.A.data &gt;= GlobalObjectsForCST.C.data))) &amp;&amp;
        ///                 (!(GlobalObjectsForCST.C.conclusion.largestParty == &quot;Bob&quot;) ||
        ///                 ((GlobalObjectsForCST.B.data &gt;= GlobalObje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Assertion {
            get {
                return ResourceManager.GetString("Assertion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Diagnostics.Contracts;
        ///using System.Text;
        ///using CST;
        ///using ABC;
        ///
        ///public interface NondetVProgram : CST.Nondet_Base
        ///{
        ///    CST.Message Message();
        ///}
        ///
        ///
        ///public class GlobalObjectsForCST
        ///{
        ///    public static A A = new A(PoirotMain.Nondet.Int());
        ///    public static B B = new B(PoirotMain.Nondet.Int());
        ///    public static C C = new C(PoirotMain.Nondet.Int());
        ///}
        ///
        ///partial class PoirotMain
        ///{
        ///    public static NondetVProgram Nondet;
        ///
        ///      static void Main()
        ///      {
        ///          Synthesiz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
    }
}
